// Builds packets from the property trees in eo-captured-packets JSON files.
//
// The PacketFromProperties and PacketsEqual functions are generated by eolib-protocol-gen (--mode test-properties)
// from the protocol XML. The helpers in the detail namespace are used by the generated code.

#pragma once

#include "eolib/protocol/net/enums.hpp"
#include "eolib/protocol/net/packet.hpp"

#include <nlohmann/json.hpp>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace eolib::test
{

using Json = nlohmann::json;

namespace client
{

/// Creates the client packet with the specified family and action, with its fields set from the properties array.
///
/// @return the packet, or nullptr if no client packet has the specified family and action.
/// @throws std::invalid_argument if a property doesn't match the packet's fields.
std::unique_ptr<protocol::net::Packet> PacketFromProperties(protocol::net::PacketFamily family,
                                                            protocol::net::PacketAction action, const Json& properties);

/// Returns true if the packets are the same client packet type, and all of their fields are equal.
bool PacketsEqual(const protocol::net::Packet& a, const protocol::net::Packet& b);

} // namespace client

namespace server
{

/// Creates the server packet with the specified family and action, with its fields set from the properties array.
///
/// @return the packet, or nullptr if no server packet has the specified family and action.
/// @throws std::invalid_argument if a property doesn't match the packet's fields.
std::unique_ptr<protocol::net::Packet> PacketFromProperties(protocol::net::PacketFamily family,
                                                            protocol::net::PacketAction action, const Json& properties);

/// Returns true if the packets are the same server packet type, and all of their fields are equal.
bool PacketsEqual(const protocol::net::Packet& a, const protocol::net::Packet& b);

} // namespace server

std::vector<std::uint8_t> DecodeBase64(const std::string& input);

namespace detail
{

const std::string& Name(const Json& property);

/// Gets the part of the property's type after the namespace, e.g. "Coords" for "protocol::Coords".
std::string TypeName(const Json& property);

/// Gets the property's children (array elements or struct fields), or an empty array if it has none.
const Json& Children(const Json& property);

/// Returns true if the property has a value or children. Optional properties without either are not present.
bool HasValue(const Json& property);

int IntValue(const Json& property);
bool BoolValue(const Json& property);
std::string StringValue(const Json& property);
std::vector<std::uint8_t> BlobValue(const Json& property);

[[noreturn]] void UnknownProperty(const Json& property, const std::string& owner);
[[noreturn]] void UnknownType(const Json& property, const std::string& owner);

template <typename T>
bool EqualAs(const protocol::net::Packet& a, const protocol::net::Packet& b)
{
    const auto* typed_a = dynamic_cast<const T*>(&a);
    const auto* typed_b = dynamic_cast<const T*>(&b);
    return typed_a != nullptr && typed_b != nullptr && *typed_a == *typed_b;
}

} // namespace detail

} // namespace eolib::test
