#include "emitter.hpp"

#include "code_writer.hpp"
#include "errors.hpp"
#include "names.hpp"

#include <algorithm>
#include <functional>
#include <map>
#include <set>

namespace eolib::generator
{

namespace
{

constexpr const char* BANNER = "// Generated by eolib-protocol-gen from eo-protocol. Do not edit.";

std::string Join(const std::vector<std::string>& parts, const std::string& separator)
{
    std::string result;
    for (std::size_t i = 0; i < parts.size(); ++i)
    {
        if (i > 0)
        {
            result += separator;
        }
        result += parts[i];
    }
    return result;
}

/// Qualified name of a custom type, relative to the namespace of the referencing file.
std::string QualifiedTypeName(const Type& type, const ProtocolFile& from)
{
    if (type.file == &from)
    {
        return type.name;
    }
    if (type.file->namespace_parts.empty())
    {
        return "protocol::" + type.name;
    }
    return Join(type.file->namespace_parts, "::") + "::" + type.name;
}

std::string CppTypeName(const Type& type, const ProtocolFile& from)
{
    switch (type.kind)
    {
        case TypeKind::Integer:
            return "int";
        case TypeKind::Bool:
            return "bool";
        case TypeKind::String:
            return "std::string";
        case TypeKind::Blob:
            return "std::vector<std::uint8_t>";
        case TypeKind::Enum:
        case TypeKind::Struct:
            return QualifiedTypeName(type, from);
    }
    throw GeneratorError("Unhandled type kind");
}

std::string OffsetExpression(int offset)
{
    if (offset == 0)
    {
        return {};
    }
    return offset > 0 ? " + " + std::to_string(offset) : " - " + std::to_string(-offset);
}

void FlattenChunked(const std::vector<Instruction>& instructions, std::vector<const Instruction*>& result)
{
    for (const auto& instruction : instructions)
    {
        result.push_back(&instruction);
        if (instruction.kind == InstructionKind::Chunked)
        {
            FlattenChunked(instruction.instructions, result);
        }
    }
}

void CollectReferencedTypes(const std::vector<Instruction>& instructions, TypeRegistry& types,
                            std::vector<const Type*>& result)
{
    for (const auto& instruction : instructions)
    {
        switch (instruction.kind)
        {
            case InstructionKind::Field:
            case InstructionKind::Array:
            case InstructionKind::Length:
            {
                const auto length =
                    instruction.kind == InstructionKind::Field ? instruction.length : std::optional<std::string>{};
                const Type& type = types.Get(instruction.type, length);
                if (type.IsCustom())
                {
                    result.push_back(&type);
                }
                break;
            }
            case InstructionKind::Switch:
                for (const auto& protocol_case : instruction.cases)
                {
                    CollectReferencedTypes(protocol_case.instructions, types, result);
                }
                break;
            case InstructionKind::Chunked:
                CollectReferencedTypes(instruction.instructions, types, result);
                break;
            default:
                break;
        }
    }
}

struct FieldData
{
    std::string identifier;
    const Type* type = nullptr;
    int offset = 0;
    bool array = false;
    bool optional = false;
    bool length_field = false;
    bool hardcoded = false;
};

struct Context
{
    bool chunked = false;
    bool reached_optional = false;
    bool reached_dummy = false;
    /// Whether a non-delimited array without a length has been reached. It consumes the rest of the data (or chunk), so
    /// it must be the final element.
    bool reached_unsized_array = false;
    std::map<std::string, FieldData> accessible_fields;
    /// Length field name -> whether it has been referenced by a field.
    std::map<std::string, bool> length_field_referenced;
    /// Length field name -> the instruction that references it.
    std::map<std::string, const Instruction*> length_references;
};

struct PacketInfo
{
    std::string family;
    std::string action;
};

/// Generates a single class (struct, packet or switch case). Follows the semantics of eolib-java's
/// ObjectCodeGenerator, FieldCodeGenerator and SwitchCodeGenerator.
class ObjectGenerator
{
public:
    ObjectGenerator(TypeRegistry& types, const ProtocolFile& file, std::string class_name, std::string qualified_name,
                    Context context)
        : types_(types),
          file_(file),
          class_name_(std::move(class_name)),
          qualified_name_(std::move(qualified_name)),
          context_(std::move(context))
    {
    }

    void GenerateInstructions(const std::vector<Instruction>& instructions)
    {
        PrepareScope(instructions);
        GenerateInstructionList(instructions);
    }

    const Context& GetContext() const
    {
        return context_;
    }

    /// Emits the class declaration and the out-of-line member definitions.
    void Finish(const std::optional<std::string>& comment, const std::optional<PacketInfo>& packet,
                CodeWriter& declaration, CodeWriter& definitions)
    {
        for (const auto& [name, referenced] : context_.length_field_referenced)
        {
            if (!referenced)
            {
                throw Error("Length field \"" + name + "\" must be referenced by another field.");
            }
        }

        if (comment)
        {
            declaration.DocComment(DocText(*comment));
        }
        const std::string base = packet ? "net::Packet" : "Serializable";
        declaration.Line("class EOLIB_API " + class_name_ + " final : public " + base);
        declaration.Line("{");
        declaration.Line("public:");
        declaration.Indent();

        if (packet)
        {
            declaration.DocComment("The packet family associated with this packet.");
            declaration.Line("static constexpr PacketFamily FAMILY = PacketFamily::" + packet->family + ";");
            declaration.Line();
            declaration.DocComment("The packet action associated with this packet.");
            declaration.Line("static constexpr PacketAction ACTION = PacketAction::" + packet->action + ";");
            declaration.Line();
        }

        if (!members_.Empty())
        {
            declaration.Append(members_);
            declaration.TrimTrailingBlankLine();
            declaration.Line();
        }

        if (packet)
        {
            declaration.DocComment("Gets the packet family associated with this packet.\n\n@return the packet family.");
            declaration.Open("PacketFamily Family() const noexcept override");
            declaration.Line("return FAMILY;");
            declaration.Close();
            declaration.Line();
            declaration.DocComment("Gets the packet action associated with this packet.\n\n@return the packet action.");
            declaration.Open("PacketAction Action() const noexcept override");
            declaration.Line("return ACTION;");
            declaration.Close();
            declaration.Line();
        }

        declaration.DocComment("Gets the size of the data that this object was deserialized from.\n\n"
                               "@return the deserialized size in bytes, or 0 for an object that was not deserialized.");
        declaration.Line("int ByteSize() const noexcept override;");
        declaration.Line();
        declaration.DocComment("Serializes this object to the provided writer.\n\n"
                               "@param writer the writer that the data will be written to.\n"
                               "@throws SerializationError if the object's data is invalid for serialization.");
        declaration.Line("void Serialize(data::EoWriter& writer) const override;");
        declaration.Line();
        declaration.DocComment("Deserializes this object from the provided reader, replacing its current data.\n\n"
                               "@param reader the reader that the data will be read from.");
        declaration.Line("void Deserialize(data::EoReader& reader) override;");
        declaration.Line();
        declaration.DocComment("Gets a human-readable representation of this object, for debugging purposes.\n\n"
                               "@return the object's fields and values, as a string.");
        declaration.Line("std::string ToString() const override;");
        declaration.Line();
        declaration.DocComment("Compares this object with another for equality. The deserialized byte size is not "
                               "compared.\n\n"
                               "@param other the object to compare with.\n"
                               "@return true if all fields are equal, otherwise false.");
        declaration.Line("bool operator==(const " + class_name_ + "& other) const;");
        declaration.Line();
        declaration.DocComment("Compares this object with another for inequality. The deserialized byte size is not "
                               "compared.\n\n"
                               "@param other the object to compare with.\n"
                               "@return true if any field differs, otherwise false.");
        declaration.Line("bool operator!=(const " + class_name_ + "& other) const;");
        declaration.Dedent();
        declaration.Line();
        declaration.Line("private:");
        declaration.Indent();
        declaration.Line("int byte_size_ = 0;");
        declaration.Dedent();
        declaration.Line("};");

        definitions.Append(nested_definitions_);

        definitions.Open("int " + qualified_name_ + "::ByteSize() const noexcept");
        definitions.Line("return byte_size_;");
        definitions.Close();
        definitions.Line();

        definitions.Open("void " + qualified_name_ + "::Serialize(data::EoWriter& writer) const");
        if (uses_chunked_)
        {
            definitions.Line("detail::StringSanitizationGuard sanitization_guard(writer);");
        }
        if (needs_old_writer_length_)
        {
            definitions.Line("const int old_writer_length = writer.Length();");
        }
        if (serialize_.Empty())
        {
            definitions.Line("(void)writer;");
        }
        definitions.Append(serialize_);
        definitions.Close();
        definitions.Line();

        definitions.Open("void " + qualified_name_ + "::Deserialize(data::EoReader& reader)");
        if (uses_chunked_)
        {
            definitions.Line("detail::ChunkedReadingModeGuard chunked_guard(reader);");
        }
        definitions.Line("*this = " + qualified_name_ + "();");
        definitions.Line("const int reader_start_position = reader.Position();");
        definitions.Append(deserialize_);
        definitions.Line("byte_size_ = reader.Position() - reader_start_position;");
        definitions.Close();
        definitions.Line();

        definitions.Open("std::string " + qualified_name_ + "::ToString() const");
        if (to_string_.empty())
        {
            definitions.Line("return \"" + class_name_ + "{}\";");
        }
        else
        {
            definitions.Line("std::string result = \"" + class_name_ + "{\";");
            for (std::size_t i = 0; i < to_string_.size(); ++i)
            {
                const auto& [label, expression] = to_string_[i];
                const std::string separator = i == 0 ? "" : ", ";
                definitions.Line("result += \"" + separator + label + "=\" + detail::FormatValue(" + expression + ");");
            }
            definitions.Line("result += \"}\";");
            definitions.Line("return result;");
        }
        definitions.Close();
        definitions.Line();

        if (equals_.empty())
        {
            definitions.Open("bool " + qualified_name_ + "::operator==(const " + qualified_name_ + "&) const");
            definitions.Line("return true;");
        }
        else
        {
            definitions.Open("bool " + qualified_name_ + "::operator==(const " + qualified_name_ + "& other) const");
            for (std::size_t i = 0; i < equals_.size(); ++i)
            {
                const std::string prefix = i == 0 ? "return " : "       ";
                const std::string suffix = i + 1 == equals_.size() ? ";" : " &&";
                definitions.Line(prefix + equals_[i] + " == other." + equals_[i] + suffix);
            }
        }
        definitions.Close();
        definitions.Line();

        definitions.Open("bool " + qualified_name_ + "::operator!=(const " + qualified_name_ + "& other) const");
        definitions.Line("return !(*this == other);");
        definitions.Close();
        definitions.Line();
    }

private:
    TypeRegistry& types_;
    const ProtocolFile& file_;
    std::string class_name_;
    std::string qualified_name_;
    Context context_;

    CodeWriter members_;
    CodeWriter nested_definitions_;
    CodeWriter serialize_;
    CodeWriter deserialize_;
    std::vector<std::pair<std::string, std::string>> to_string_;
    std::vector<std::string> equals_;
    std::set<std::string> scope_identifiers_;
    bool needs_old_writer_length_ = false;
    bool declared_reached_null_optional_ = false;
    bool uses_chunked_ = false;

    // Set while generating an instruction: true if a <dummy> follows the instruction in the same list.
    bool dummy_follows_ = false;

    GeneratorError Error(const std::string& message) const
    {
        return GeneratorError(file_.path.string() + ": " + qualified_name_ + ": " + message);
    }

    /// Records identifiers and length field references for the instructions of this object.
    void PrepareScope(const std::vector<Instruction>& instructions)
    {
        std::vector<const Instruction*> flattened;
        FlattenChunked(instructions, flattened);
        for (const auto* instruction : flattened)
        {
            if (instruction->name)
            {
                scope_identifiers_.insert(MemberIdentifier(*instruction->name));
            }
            if ((instruction->kind == InstructionKind::Field || instruction->kind == InstructionKind::Array) &&
                instruction->length && !IsInteger(*instruction->length))
            {
                if (context_.length_references.count(*instruction->length) != 0)
                {
                    throw Error("Length field \"" + *instruction->length +
                                "\" must not be referenced by multiple fields.");
                }
                context_.length_references[*instruction->length] = instruction;
            }
        }
    }

    std::string LocalName(const std::string& base) const
    {
        std::string result = base;
        while (scope_identifiers_.count(result) != 0 || IsReservedIdentifier(result))
        {
            result += "_";
        }
        return result;
    }

    void GenerateInstructionList(const std::vector<Instruction>& instructions)
    {
        for (std::size_t i = 0; i < instructions.size(); ++i)
        {
            dummy_follows_ = std::any_of(instructions.begin() + static_cast<std::ptrdiff_t>(i) + 1, instructions.end(),
                                         [](const Instruction& x) { return x.kind == InstructionKind::Dummy; });
            GenerateInstruction(instructions[i]);
        }
    }

    void GenerateInstruction(const Instruction& instruction)
    {
        if (context_.reached_dummy)
        {
            throw Error("<dummy> elements must not be followed by any other elements.");
        }
        if (context_.reached_unsized_array && instruction.kind != InstructionKind::Break)
        {
            throw Error("Non-delimited arrays without a length must be the final element (or the final element in the "
                        "chunk, if chunked reading is enabled).");
        }

        switch (instruction.kind)
        {
            case InstructionKind::Field:
                GenerateField(instruction);
                break;
            case InstructionKind::Array:
                GenerateArray(instruction);
                break;
            case InstructionKind::Length:
                GenerateLength(instruction);
                break;
            case InstructionKind::Dummy:
                GenerateDummy(instruction);
                break;
            case InstructionKind::Switch:
                GenerateSwitch(instruction);
                break;
            case InstructionKind::Chunked:
                GenerateChunked(instruction);
                break;
            case InstructionKind::Break:
                GenerateBreak();
                break;
        }
    }

    void CheckOptionalField(bool optional) const
    {
        if (context_.reached_optional && !optional)
        {
            throw Error("Optional fields may not be followed by non-optional fields.");
        }
    }

    void CheckUniqueName(const std::string& name) const
    {
        if (context_.accessible_fields.count(name) != 0)
        {
            throw Error("Cannot redefine " + name + " field.");
        }
    }

    void AddMemberDocs(const Instruction& instruction, const std::vector<std::string>& notes)
    {
        std::string docs = DocText(instruction.comment.value_or(""));
        if (!notes.empty())
        {
            if (!docs.empty())
            {
                docs += "\n\n";
            }
            docs += "@note";
            for (const auto& note : notes)
            {
                docs += "\n- " + note;
            }
        }
        if (!docs.empty())
        {
            members_.DocComment(docs);
        }
    }

    std::vector<std::string> MemberNotes(const Instruction& instruction, const Type& type, bool array) const
    {
        std::vector<std::string> notes;
        if (instruction.length)
        {
            std::string description;
            const auto length_field = context_.accessible_fields.find(*instruction.length);
            if (length_field != context_.accessible_fields.end())
            {
                description =
                    std::to_string(MaxValueOf(*length_field->second.type) + length_field->second.offset) + " or less";
            }
            else
            {
                description = "`" + *instruction.length + "`";
                if (instruction.padded)
                {
                    description += " or less";
                }
            }
            notes.push_back(std::string(array ? "Size" : "Length") + " must be " + description + ".");
        }
        if (type.kind == TypeKind::Integer)
        {
            notes.push_back(std::string(array ? "Element value" : "Value") + " range is 0-" +
                            std::to_string(MaxValueOf(type)) + ".");
        }
        return notes;
    }

    // ---- Serialization helpers ----

    /// Begins the optional guard for serialization, if the field is optional.
    void BeginSerializeOptional(const FieldData& field)
    {
        const std::string null_check = "!" + field.identifier + ".has_value()";
        if (context_.reached_optional && declared_reached_null_optional_)
        {
            serialize_.Line("reached_null_optional = reached_null_optional || " + null_check + ";");
        }
        else if (declared_reached_null_optional_)
        {
            serialize_.Line("reached_null_optional = " + null_check + ";");
        }
        else
        {
            serialize_.Line("bool reached_null_optional = " + null_check + ";");
            declared_reached_null_optional_ = true;
        }
        serialize_.Open("if (!reached_null_optional)");
    }

    void BeginDeserializeOptional(const Type& type, bool array)
    {
        if (dummy_follows_ && !array && type.fixed_size)
        {
            deserialize_.Open("if (reader.Remaining() >= " + std::to_string(*type.fixed_size) + ")");
        }
        else
        {
            deserialize_.Open("if (reader.Remaining() > 0)");
        }
    }

    static std::string WriteMethod(const Type& type)
    {
        const std::string& name = type.name;
        if (name == "byte")
        {
            return "AddByte";
        }
        if (name == "char")
        {
            return "AddChar";
        }
        if (name == "short")
        {
            return "AddShort";
        }
        if (name == "three")
        {
            return "AddThree";
        }
        if (name == "int")
        {
            return "AddInt";
        }
        throw GeneratorError("Unhandled integer type " + name);
    }

    static std::string ReadMethod(const Type& type)
    {
        const std::string& name = type.name;
        if (name == "byte")
        {
            return "GetByte";
        }
        if (name == "char")
        {
            return "GetChar";
        }
        if (name == "short")
        {
            return "GetShort";
        }
        if (name == "three")
        {
            return "GetThree";
        }
        if (name == "int")
        {
            return "GetInt";
        }
        throw GeneratorError("Unhandled integer type " + name);
    }

    /// Returns a statement that writes the value expression.
    std::string WriteStatement(const Type& type, const std::string& value, const std::optional<std::string>& length,
                               bool padded) const
    {
        const Type& serialization_type = type.SerializationType();
        std::string expression = value;
        if (type.kind == TypeKind::Enum)
        {
            expression = "static_cast<int>(" + value + ")";
        }
        else if (type.kind == TypeKind::Bool)
        {
            expression = value + " ? 1 : 0";
        }

        switch (serialization_type.kind)
        {
            case TypeKind::Integer:
                return "writer." + WriteMethod(serialization_type) + "(" + expression + ");";
            case TypeKind::String:
            {
                const bool encoded = serialization_type.name == "encoded_string";
                if (!length)
                {
                    return std::string("writer.") + (encoded ? "AddEncodedString" : "AddString") + "(" + expression +
                           ");";
                }
                return std::string("writer.") + (encoded ? "AddFixedEncodedString" : "AddFixedString") + "(" +
                       expression + ", " + *length + (padded ? ", true" : "") + ");";
            }
            case TypeKind::Blob:
                return "writer.AddBytes(" + expression + ");";
            case TypeKind::Struct:
                return expression + ".Serialize(writer);";
            default:
                throw Error("Unhandled type for serialization: " + type.name);
        }
    }

    /// Returns an expression that reads a value of the specified basic/enum/blob type.
    std::string ReadExpression(const Type& type, const std::optional<std::string>& length, bool padded,
                               int offset = 0) const
    {
        const Type& serialization_type = type.SerializationType();
        std::string expression;
        switch (serialization_type.kind)
        {
            case TypeKind::Integer:
                expression = "reader." + ReadMethod(serialization_type) + "()" + OffsetExpression(offset);
                break;
            case TypeKind::String:
            {
                const bool encoded = serialization_type.name == "encoded_string";
                if (!length)
                {
                    expression = std::string("reader.") + (encoded ? "GetEncodedString" : "GetString") + "()";
                }
                else
                {
                    expression = std::string("reader.") + (encoded ? "GetFixedEncodedString" : "GetFixedString") + "(" +
                                 *length + (padded ? ", true" : "") + ")";
                }
                break;
            }
            case TypeKind::Blob:
                expression = "reader.GetBytes(reader.Remaining())";
                break;
            default:
                throw Error("Unhandled type for deserialization: " + type.name);
        }

        if (type.kind == TypeKind::Enum)
        {
            return "static_cast<" + CppTypeName(type, file_) + ">(" + expression + ")";
        }
        if (type.kind == TypeKind::Bool)
        {
            return expression + " != 0";
        }
        return expression;
    }

    /// Returns the literal expression for a hardcoded value.
    std::string HardcodedValueExpression(const Type& type, const std::string& value) const
    {
        switch (type.kind)
        {
            case TypeKind::Integer:
                if (!IsInteger(value))
                {
                    throw Error("\"" + value + "\" is not a valid integer value.");
                }
                return value;
            case TypeKind::Bool:
                if (value == "false")
                {
                    return "false";
                }
                if (value == "true")
                {
                    return "true";
                }
                throw Error("\"" + value + "\" is not a valid bool value.");
            case TypeKind::String:
                return StringLiteral(value);
            default:
                throw Error("Hardcoded field values are not allowed for " + type.name +
                            " fields (must be a basic type).");
        }
    }

    /// For a length field reference in a field/array, returns the expression used when deserializing.
    std::optional<std::string> DeserializeLengthExpression(const std::optional<std::string>& length) const
    {
        if (!length)
        {
            return std::nullopt;
        }
        if (IsInteger(*length))
        {
            return length;
        }
        const auto it = context_.accessible_fields.find(*length);
        if (it == context_.accessible_fields.end() || !it->second.length_field)
        {
            throw Error("Referenced " + *length + " field is not accessible.");
        }
        return it->second.identifier;
    }

    void ValidateLengthAttribute(const std::optional<std::string>& length)
    {
        if (!length)
        {
            return;
        }
        if (IsInteger(*length))
        {
            return;
        }
        const auto it = context_.length_field_referenced.find(*length);
        if (it == context_.length_field_referenced.end())
        {
            throw Error("Length attribute \"" + *length + "\" must be a numeric literal, or refer to a length field.");
        }
        if (it->second)
        {
            throw Error("Length field \"" + *length + "\" must not be referenced by multiple fields.");
        }
        it->second = true;
    }

    // ---- Instruction generators ----

    void GenerateField(const Instruction& instruction)
    {
        CheckOptionalField(instruction.optional);

        const Type& type = types_.Get(instruction.type, instruction.length);
        ValidateField(instruction, type);

        const FieldData field = DeclareField(instruction, type);
        GenerateSerializeField(instruction, type, field);
        GenerateDeserializeField(instruction, type, field);

        if (instruction.optional)
        {
            context_.reached_optional = true;
        }
    }

    void ValidateField(const Instruction& instruction, const Type& type)
    {
        if (!instruction.name)
        {
            if (!instruction.value)
            {
                throw Error("Unnamed fields must specify a hardcoded field value.");
            }
            if (instruction.optional)
            {
                throw Error("Unnamed fields may not be optional.");
            }
        }
        if (instruction.value)
        {
            if (!type.IsBasic())
            {
                throw Error("Hardcoded field values are not allowed for " + type.name +
                            " fields (must be a basic type).");
            }
            if (type.kind == TypeKind::String && type.fixed_size &&
                static_cast<std::size_t>(*type.fixed_size) != instruction.value->size())
            {
                throw Error("Expected length of " + std::to_string(*type.fixed_size) +
                            " for hardcoded string value \"" + *instruction.value + "\".");
            }
            if (instruction.length && !IsInteger(*instruction.length))
            {
                throw Error("Hardcoded fields must not reference a length field.");
            }
        }
        if ((instruction.length || instruction.padded) && type.kind != TypeKind::String)
        {
            throw Error("length and padded attributes are only allowed for string types.");
        }
        if (instruction.padded && !instruction.length)
        {
            throw Error("Padded fields must specify a length.");
        }
        ValidateLengthAttribute(instruction.length);
    }

    FieldData DeclareField(const Instruction& instruction, const Type& type)
    {
        FieldData field;
        field.type = &type;
        field.optional = instruction.optional;
        field.hardcoded = instruction.value.has_value();

        if (!instruction.name)
        {
            return field;
        }

        CheckUniqueName(*instruction.name);
        field.identifier = MemberIdentifier(*instruction.name);
        AddMemberDocs(instruction, MemberNotes(instruction, type, false));

        if (field.hardcoded)
        {
            const std::string value = HardcodedValueExpression(type, *instruction.value);
            const std::string cpp_type = type.kind == TypeKind::String ? "std::string_view" : CppTypeName(type, file_);
            members_.Line("static constexpr " + cpp_type + " " + field.identifier + " = " + value + ";");
        }
        else
        {
            std::string cpp_type = CppTypeName(type, file_);
            if (instruction.optional)
            {
                cpp_type = "std::optional<" + cpp_type + ">";
            }
            members_.Line(cpp_type + " " + field.identifier + "{};");
            equals_.push_back(field.identifier);
            to_string_.emplace_back(field.identifier, field.identifier);
        }
        members_.Line();
        context_.accessible_fields[*instruction.name] = field;
        return field;
    }

    void GenerateSerializeField(const Instruction& instruction, const Type& type, const FieldData& field)
    {
        if (instruction.optional)
        {
            BeginSerializeOptional(field);
        }

        std::string value;
        if (!instruction.name)
        {
            value = HardcodedValueExpression(type, *instruction.value);
        }
        else
        {
            value = instruction.optional ? "(*" + field.identifier + ")" : field.identifier;
        }

        std::optional<std::string> serialize_length;
        if (instruction.length)
        {
            if (IsInteger(*instruction.length))
            {
                serialize_length = *instruction.length;
                if (instruction.name && !field.hardcoded)
                {
                    GenerateSerializeLengthCheck(field.identifier, value + ".size()", *instruction.length,
                                                 instruction.padded);
                }
            }
            else
            {
                serialize_length = "static_cast<int>(" + value + ".size())";
            }
        }
        serialize_.Line(WriteStatement(type, value, serialize_length, instruction.padded));

        if (instruction.optional)
        {
            serialize_.Close();
        }
    }

    void GenerateDeserializeField(const Instruction& instruction, const Type& type, const FieldData& field)
    {
        if (instruction.optional)
        {
            BeginDeserializeOptional(type, false);
        }

        const auto deserialize_length = DeserializeLengthExpression(instruction.length);
        if (!instruction.name || field.hardcoded)
        {
            deserialize_.Line(ReadExpression(type.SerializationType(), deserialize_length, instruction.padded) + ";");
        }
        else if (type.kind == TypeKind::Struct)
        {
            const std::string target = instruction.optional ? field.identifier + ".emplace()" : field.identifier;
            deserialize_.Line(target + ".Deserialize(reader);");
        }
        else
        {
            deserialize_.Line(field.identifier + " = " + ReadExpression(type, deserialize_length, instruction.padded) +
                              ";");
        }

        if (instruction.optional)
        {
            deserialize_.Close();
        }
    }

    /// Emits a check that a sized field fits its length: exactly equal, or at most the limit if allow_shorter is set.
    void GenerateSerializeLengthCheck(const std::string& identifier, const std::string& size_expression,
                                      const std::string& limit, bool allow_shorter)
    {
        const std::string op = allow_shorter ? ">" : "!=";
        const std::string expected = allow_shorter ? limit + " or less" : "exactly " + limit;
        serialize_.Open("if (" + size_expression + " " + op + " " + limit + ")");
        serialize_.Line("throw SerializationError(\"Expected " + identifier + ".size() to be " + expected +
                        ", got \" + std::to_string(" + size_expression + ") + \".\");");
        serialize_.Close();
    }

    void GenerateArray(const Instruction& instruction)
    {
        CheckOptionalField(instruction.optional);

        if (instruction.delimited && !context_.chunked)
        {
            throw Error("Cannot generate a delimited array instruction unless chunked reading is enabled. (All "
                        "delimited <array> elements must be within <chunked> sections.)");
        }

        const Type& type = types_.Get(instruction.type);
        ValidateArray(instruction, type);

        const FieldData field = DeclareArray(instruction, type);
        const std::string container = instruction.optional ? "(*" + field.identifier + ")" : field.identifier;
        const bool trailing_delimiter = instruction.delimited && instruction.trailing_delimiter.value_or(true);
        GenerateSerializeArray(instruction, type, field, container, trailing_delimiter);
        GenerateDeserializeArray(instruction, type, field, container, trailing_delimiter);

        if (instruction.optional)
        {
            context_.reached_optional = true;
        }
        if (!instruction.delimited && !instruction.length)
        {
            context_.reached_unsized_array = true;
        }
    }

    void ValidateArray(const Instruction& instruction, const Type& type)
    {
        if (!instruction.delimited && !type.bounded)
        {
            throw Error("Unbounded element type (" + instruction.type + ") forbidden in non-delimited array.");
        }
        if (!instruction.delimited && instruction.trailing_delimiter)
        {
            throw Error("Only delimited arrays can have a trailing delimiter.");
        }
        ValidateLengthAttribute(instruction.length);
        CheckUniqueName(*instruction.name);
    }

    FieldData DeclareArray(const Instruction& instruction, const Type& type)
    {
        FieldData field;
        field.identifier = MemberIdentifier(*instruction.name);
        field.type = &type;
        field.array = true;
        field.optional = instruction.optional;

        AddMemberDocs(instruction, MemberNotes(instruction, type, true));
        std::string cpp_type = "std::vector<" + CppTypeName(type, file_) + ">";
        if (instruction.optional)
        {
            cpp_type = "std::optional<" + cpp_type + ">";
        }
        members_.Line(cpp_type + " " + field.identifier + "{};");
        members_.Line();
        equals_.push_back(field.identifier);
        to_string_.emplace_back(field.identifier, field.identifier);
        context_.accessible_fields[*instruction.name] = field;
        return field;
    }

    void GenerateSerializeArray(const Instruction& instruction, const Type& type, const FieldData& field,
                                const std::string& container, bool trailing_delimiter)
    {
        if (instruction.optional)
        {
            BeginSerializeOptional(field);
        }

        if (instruction.length && IsInteger(*instruction.length))
        {
            GenerateSerializeLengthCheck(field.identifier, container + ".size()", *instruction.length, false);
        }

        serialize_.Open("for (std::size_t i = 0; i < " + container + ".size(); ++i)");
        if (instruction.delimited && !trailing_delimiter)
        {
            serialize_.Open("if (i > 0)");
            serialize_.Line("writer.AddByte(0xFF);");
            serialize_.Close();
        }
        serialize_.Line(WriteStatement(type, container + "[i]", std::nullopt, false));
        if (trailing_delimiter)
        {
            serialize_.Line("writer.AddByte(0xFF);");
        }
        serialize_.Close();

        if (instruction.optional)
        {
            serialize_.Close();
        }
    }

    void GenerateDeserializeArray(const Instruction& instruction, const Type& type, const FieldData& field,
                                  const std::string& container, bool trailing_delimiter)
    {
        if (instruction.optional)
        {
            BeginDeserializeOptional(type, true);
            deserialize_.Line(field.identifier + ".emplace();");
        }

        std::optional<std::string> length = DeserializeLengthExpression(instruction.length);
        if (!length && !instruction.delimited && type.fixed_size)
        {
            const std::string size_variable = LocalName(field.identifier + "_size");
            deserialize_.Line("const int " + size_variable + " = reader.Remaining() / " +
                              std::to_string(*type.fixed_size) + ";");
            length = size_variable;
        }

        deserialize_.Open(length ? "for (int i = 0; i < " + *length + "; ++i)" : "while (reader.Remaining() > 0)");

        if (type.kind == TypeKind::Struct)
        {
            deserialize_.Line(container + ".emplace_back().Deserialize(reader);");
        }
        else
        {
            deserialize_.Line(container + ".push_back(" + ReadExpression(type, std::nullopt, false) + ");");
        }

        if (instruction.delimited)
        {
            const bool needs_guard = !trailing_delimiter && length;
            if (needs_guard)
            {
                deserialize_.Open("if (i + 1 < " + *length + ")");
            }
            deserialize_.Line("reader.NextChunk();");
            if (needs_guard)
            {
                deserialize_.Close();
            }
        }
        deserialize_.Close();

        if (instruction.optional)
        {
            deserialize_.Close();
        }
    }

    void GenerateLength(const Instruction& instruction)
    {
        CheckOptionalField(instruction.optional);

        const Type& type = types_.Get(instruction.type);
        const std::string& name = *instruction.name;
        if (type.kind != TypeKind::Integer)
        {
            throw Error(type.name + " is not a numeric type, so it is not allowed for a length field.");
        }
        CheckUniqueName(name);

        const auto reference = context_.length_references.find(name);
        if (reference == context_.length_references.end())
        {
            throw Error("Length field \"" + name + "\" must be referenced by another field.");
        }
        const Instruction& referencing = *reference->second;
        if (referencing.value || !referencing.name)
        {
            throw Error("Hardcoded fields must not reference a length field.");
        }
        const std::string referencing_identifier = MemberIdentifier(*referencing.name);

        FieldData field;
        field.identifier = MemberIdentifier(name);
        field.type = &type;
        field.offset = instruction.offset;
        field.length_field = true;
        field.optional = instruction.optional;
        context_.accessible_fields[name] = field;
        context_.length_field_referenced[name] = false;

        // Serialize: the value is computed from the size of the referencing field.
        if (instruction.optional)
        {
            BeginSerializeOptional(FieldData{referencing_identifier, &type, 0, false, true, false, false});
        }

        const std::string size_expression = referencing.optional
                                                ? "(" + referencing_identifier + ".has_value() ? static_cast<int>(" +
                                                      referencing_identifier + "->size()) : 0)"
                                                : "static_cast<int>(" + referencing_identifier + ".size())";

        const long long max_size = MaxValueOf(type) + instruction.offset;
        if (max_size < 0x7FFFFFFFLL)
        {
            GenerateSerializeLengthCheck(referencing_identifier, size_expression, std::to_string(max_size), true);
        }
        serialize_.Line(
            WriteStatement(type, size_expression + OffsetExpression(-instruction.offset), std::nullopt, false));

        if (instruction.optional)
        {
            serialize_.Close();
        }

        // Deserialize: the value is stored in a local variable, referenced by the field that follows.
        const std::string read = ReadExpression(type, std::nullopt, false, instruction.offset);
        if (instruction.optional)
        {
            deserialize_.Line("int " + field.identifier + " = 0;");
            BeginDeserializeOptional(type, false);
            deserialize_.Line(field.identifier + " = " + read + ";");
            deserialize_.Close();
            context_.reached_optional = true;
        }
        else
        {
            deserialize_.Line("const int " + field.identifier + " = " + read + ";");
        }
    }

    void GenerateDummy(const Instruction& instruction)
    {
        const Type& type = types_.Get(instruction.type);
        if (!type.IsBasic())
        {
            throw Error("Dummy fields must be a basic type.");
        }

        const bool needs_guards = !serialize_.Empty() || !deserialize_.Empty();
        if (needs_guards)
        {
            serialize_.Open("if (writer.Length() == old_writer_length)");
            deserialize_.Open("if (reader.Position() == reader_start_position)");
        }

        serialize_.Line(WriteStatement(type, HardcodedValueExpression(type, *instruction.value), std::nullopt, false));
        deserialize_.Line(ReadExpression(type.SerializationType(), std::nullopt, false) + ";");

        if (needs_guards)
        {
            serialize_.Close();
            deserialize_.Close();
            needs_old_writer_length_ = true;
        }

        context_.reached_dummy = true;
    }

    void GenerateChunked(const Instruction& instruction)
    {
        const bool was_already_enabled = context_.chunked;
        if (!was_already_enabled)
        {
            context_.chunked = true;
            uses_chunked_ = true;
            deserialize_.Line("reader.SetChunkedReadingMode(true);");
            serialize_.Line("writer.SetStringSanitization(true);");
        }

        const bool outer_dummy_follows = dummy_follows_;
        GenerateInstructionList(instruction.instructions);
        dummy_follows_ = outer_dummy_follows;

        if (!was_already_enabled)
        {
            context_.chunked = false;
            deserialize_.Line("reader.SetChunkedReadingMode(false);");
            serialize_.Line("writer.SetStringSanitization(false);");
        }
    }

    void GenerateBreak()
    {
        if (!context_.chunked)
        {
            throw Error("Cannot generate a break instruction unless chunked reading is enabled. (All <break> "
                        "elements must be within <chunked> sections.)");
        }

        context_.reached_optional = false;
        context_.reached_dummy = false;
        context_.reached_unsized_array = false;

        deserialize_.Line("reader.NextChunk();");
        serialize_.Line("writer.AddByte(0xFF);");
    }

    /// Code generated for the cases of a switch instruction.
    struct SwitchCases
    {
        std::vector<std::string> alternatives = {"std::monostate"};
        CodeWriter serialize;
        CodeWriter deserialize;
        bool reached_optional = false;
        bool reached_dummy = false;
        bool reached_unsized_array = false;
    };

    void GenerateSwitch(const Instruction& instruction)
    {
        const std::string& field_name = instruction.switch_field;
        const FieldData& field = GetSwitchField(field_name);

        const std::string data_type_name = SnakeCaseToPascalCase(field_name) + "Data";
        const std::string data_field_name = MemberIdentifier(field_name + "_data");
        if (context_.accessible_fields.count(field_name + "_data") != 0 ||
            scope_identifiers_.count(data_field_name) != 0)
        {
            throw Error("Switch data field " + data_field_name + " conflicts with an existing field.");
        }

        // Switching on an enum with values that are not enumerators triggers -Wswitch, so switch on the integer value
        // instead in that case.
        const bool integer_switch =
            field.type->kind == TypeKind::Enum &&
            std::any_of(instruction.cases.begin(), instruction.cases.end(),
                        [](const ProtocolCase& x) { return !x.is_default && IsInteger(*x.value); });
        const std::string switch_expression =
            integer_switch ? "static_cast<int>(" + field.identifier + ")" : field.identifier;

        const bool has_default = ValidateSwitchCases(instruction, field, integer_switch);

        SwitchCases cases;
        cases.reached_optional = context_.reached_optional;
        cases.reached_dummy = context_.reached_dummy;
        cases.reached_unsized_array = context_.reached_unsized_array;

        for (const auto& protocol_case : instruction.cases)
        {
            const std::string label =
                protocol_case.is_default
                    ? "default:"
                    : "case " + CaseValueExpression(field, *protocol_case.value, integer_switch) + ":";

            if (protocol_case.instructions.empty())
            {
                GenerateEmptyCase(field, data_field_name, label, cases);
            }
            else
            {
                GenerateDataCase(protocol_case, field, data_type_name, data_field_name, label, cases);
            }
        }

        if (!has_default)
        {
            for (CodeWriter* writer : {&cases.serialize, &cases.deserialize})
            {
                writer->Line("default:");
                writer->Indent();
                writer->Line("break;");
                writer->Dedent();
            }
        }

        std::string data_docs = "Data associated with the `" + field.identifier + "` field.";
        if (instruction.comment)
        {
            data_docs += "\n\n" + DocText(*instruction.comment);
        }
        members_.DocComment("Data associated with different values of the `" + field.identifier + "` field.");
        members_.Line("using " + data_type_name + " = std::variant<" + Join(cases.alternatives, ", ") + ">;");
        members_.Line();
        members_.DocComment(data_docs);
        members_.Line(data_type_name + " " + data_field_name + "{};");
        members_.Line();

        serialize_.Open("switch (" + switch_expression + ")");
        serialize_.Append(cases.serialize);
        serialize_.Close();

        deserialize_.Open("switch (" + switch_expression + ")");
        deserialize_.Append(cases.deserialize);
        deserialize_.Close();

        context_.reached_optional = cases.reached_optional;
        context_.reached_dummy = cases.reached_dummy;
        context_.reached_unsized_array = cases.reached_unsized_array;

        equals_.push_back(data_field_name);
        to_string_.emplace_back(data_field_name, data_field_name);
    }

    const FieldData& GetSwitchField(const std::string& field_name) const
    {
        const auto field_it = context_.accessible_fields.find(field_name);
        if (field_it == context_.accessible_fields.end())
        {
            throw Error("Referenced " + field_name + " field is not accessible.");
        }

        const FieldData& field = field_it->second;
        if (field.array)
        {
            throw Error("\"" + field_name + "\" field referenced by switch must not be an array.");
        }
        if (field.optional || field.length_field || field.hardcoded)
        {
            throw Error("\"" + field_name +
                        "\" field referenced by switch must be unconditionally present (not optional, a length "
                        "field or hardcoded).");
        }
        if (field.type->kind != TypeKind::Integer && field.type->kind != TypeKind::Enum)
        {
            throw Error(field_name + " field referenced by switch must be a numeric or enumeration type.");
        }
        return field;
    }

    /// Validates case ordering and uniqueness. Returns true if the switch has a default case.
    bool ValidateSwitchCases(const Instruction& instruction, const FieldData& field, bool integer_switch) const
    {
        bool reached_default = false;
        std::set<std::string> case_values;
        for (const auto& protocol_case : instruction.cases)
        {
            if (reached_default)
            {
                throw Error("Only the last case in a switch can be the default case.");
            }
            if (protocol_case.is_default)
            {
                reached_default = true;
            }
            else if (!case_values.insert(CaseValueExpression(field, *protocol_case.value, integer_switch)).second)
            {
                throw Error("Duplicate case value " + *protocol_case.value + " in switch on " +
                            instruction.switch_field + ".");
            }
        }
        return reached_default;
    }

    void GenerateEmptyCase(const FieldData& field, const std::string& data_field_name, const std::string& label,
                           SwitchCases& cases) const
    {
        cases.serialize.Line(label);
        cases.serialize.Indent();
        cases.serialize.Open("if (!std::holds_alternative<std::monostate>(" + data_field_name + "))");
        cases.serialize.Line("throw SerializationError(\"Expected " + data_field_name + " to be empty for " +
                             field.identifier + " \" + detail::FormatValue(" + field.identifier + ") + \".\");");
        cases.serialize.Close();
        cases.serialize.Line("break;");
        cases.serialize.Dedent();

        cases.deserialize.Line(label);
        cases.deserialize.Indent();
        cases.deserialize.Line(data_field_name + " = std::monostate();");
        cases.deserialize.Line("break;");
        cases.deserialize.Dedent();
    }

    void GenerateDataCase(const ProtocolCase& protocol_case, const FieldData& field, const std::string& data_type_name,
                          const std::string& data_field_name, const std::string& label, SwitchCases& cases)
    {
        const std::string case_type_name =
            data_type_name + (protocol_case.is_default ? std::string("Default") : *protocol_case.value);
        const std::string description =
            protocol_case.is_default ? "default" : "value " + CaseValueDescription(field, *protocol_case.value);

        Context case_context;
        case_context.chunked = context_.chunked;
        case_context.reached_optional = context_.reached_optional;
        case_context.reached_dummy = context_.reached_dummy;
        case_context.reached_unsized_array = context_.reached_unsized_array;

        ObjectGenerator case_generator(types_, file_, case_type_name, qualified_name_ + "::" + case_type_name,
                                       case_context);
        case_generator.GenerateInstructions(protocol_case.instructions);

        std::string docs = "Data associated with " + field.identifier + " " + description + ".";
        if (protocol_case.comment)
        {
            docs += "\n\n" + DocText(*protocol_case.comment);
        }

        CodeWriter case_declaration;
        case_generator.Finish(docs, std::nullopt, case_declaration, nested_definitions_);
        members_.Append(case_declaration);
        members_.Line();
        cases.alternatives.push_back(case_type_name);

        cases.reached_optional = cases.reached_optional || case_generator.GetContext().reached_optional;
        cases.reached_dummy = cases.reached_dummy || case_generator.GetContext().reached_dummy;
        cases.reached_unsized_array = cases.reached_unsized_array || case_generator.GetContext().reached_unsized_array;

        cases.serialize.Line(label);
        cases.serialize.Line("{");
        cases.serialize.Indent();
        cases.serialize.Line("const auto* case_data = std::get_if<" + case_type_name + ">(&" + data_field_name + ");");
        cases.serialize.Open("if (case_data == nullptr)");
        cases.serialize.Line("throw SerializationError(\"Expected " + data_field_name + " to be type " +
                             case_type_name + " for " + field.identifier + " \" + detail::FormatValue(" +
                             field.identifier + ") + \".\");");
        cases.serialize.Close();
        cases.serialize.Line("case_data->Serialize(writer);");
        cases.serialize.Line("break;");
        cases.serialize.Close();

        cases.deserialize.Line(label);
        cases.deserialize.Indent();
        cases.deserialize.Line(data_field_name + ".emplace<" + case_type_name + ">().Deserialize(reader);");
        cases.deserialize.Line("break;");
        cases.deserialize.Dedent();
    }

    std::string CaseValueExpression(const FieldData& field, const std::string& value, bool integer_switch) const
    {
        if (field.type->kind == TypeKind::Integer)
        {
            if (!IsInteger(value))
            {
                throw Error("\"" + value + "\" is not a valid integer value.");
            }
            return value;
        }

        const auto& protocol_enum = *field.type->enum_definition;
        const std::string enum_name = CppTypeName(*field.type, file_);
        if (IsInteger(value))
        {
            const long long ordinal = std::stoll(value);
            for (const auto& enum_value : protocol_enum.values)
            {
                if (enum_value.ordinal == ordinal)
                {
                    throw Error(protocol_enum.name + " value " + value + " must be referred to by name (" +
                                enum_value.name + ")");
                }
            }
            return integer_switch ? value : "static_cast<" + enum_name + ">(" + value + ")";
        }

        for (const auto& enum_value : protocol_enum.values)
        {
            if (enum_value.name == value)
            {
                return integer_switch ? "static_cast<int>(" + enum_name + "::" + value + ")" : enum_name + "::" + value;
            }
        }
        throw Error("\"" + value + "\" is not a valid value for enum type " + protocol_enum.name);
    }

    std::string CaseValueDescription(const FieldData& field, const std::string& value) const
    {
        if (field.type->kind == TypeKind::Enum && IsInteger(value))
        {
            return "Unrecognized(" + value + ")";
        }
        return value;
    }
};

class ProtocolGenerator
{
public:
    ProtocolGenerator(const std::vector<ProtocolFile>& files, TypeRegistry& types)
        : files_(files),
          types_(types)
    {
    }

    std::vector<OutputFile> Generate()
    {
        std::vector<OutputFile> result;
        for (const auto& file : files_)
        {
            const auto layout = FileLayout::Of(file);
            if (layout.has_enums)
            {
                GenerateEnums(file, result);
            }
            if (layout.has_structs)
            {
                GenerateStructs(file, result);
            }
            if (layout.has_packets)
            {
                GeneratePackets(file, result);
                GeneratePacketFactory(file, result);
            }
            if (!file.namespace_parts.empty())
            {
                GenerateUmbrella(file, result);
            }
        }
        GenerateRootUmbrella(result);
        return result;
    }

private:
    const std::vector<ProtocolFile>& files_;
    TypeRegistry& types_;

    static std::string HeaderPath(const ProtocolFile& file, const std::string& name)
    {
        return file.IncludeDir() + "/" + name + ".hpp";
    }

    static void BeginHeader(CodeWriter& writer)
    {
        writer.Line(BANNER);
        writer.Line();
        writer.Line("#pragma once");
        writer.Line();
    }

    static void Includes(CodeWriter& writer, const std::set<std::string>& local, const std::set<std::string>& system)
    {
        for (const auto& include : local)
        {
            writer.Line("#include \"" + include + "\"");
        }
        if (!local.empty() && !system.empty())
        {
            writer.Line();
        }
        for (const auto& include : system)
        {
            writer.Line("#include <" + include + ">");
        }
        writer.Line();
    }

    static void BeginNamespace(CodeWriter& writer, const ProtocolFile& file)
    {
        writer.Line("namespace " + file.Namespace());
        writer.Line("{");
        writer.Line();
    }

    static void EndNamespace(CodeWriter& writer, const ProtocolFile& file)
    {
        writer.TrimTrailingBlankLine();
        writer.Line();
        writer.Line("} // namespace " + file.Namespace());
    }

    static void AddOutput(std::vector<OutputFile>& result, const std::string& path, const CodeWriter& writer)
    {
        result.push_back(OutputFile{path, writer.ToString()});
    }

    void GenerateEnums(const ProtocolFile& file, std::vector<OutputFile>& result)
    {
        CodeWriter header;
        BeginHeader(header);
        Includes(header, {"eolib/export.hpp"}, {"iosfwd", "string"});
        BeginNamespace(header, file);

        CodeWriter source;
        source.Line(BANNER);
        source.Line();
        Includes(source, {HeaderPath(file, "enums")}, {"ostream", "string"});
        BeginNamespace(source, file);

        for (const auto& protocol_enum : file.enums)
        {
            // Validates the enum and its underlying type.
            types_.Get(protocol_enum.name);

            if (protocol_enum.comment)
            {
                header.DocComment(DocText(*protocol_enum.comment));
            }
            header.Line("enum class " + protocol_enum.name + " : int");
            header.Line("{");
            header.Indent();
            for (const auto& value : protocol_enum.values)
            {
                if (value.ordinal < -2147483648LL || value.ordinal > 2147483647LL)
                {
                    throw GeneratorError(file.path.string() + ": " + protocol_enum.name + "." + value.name +
                                         " ordinal value is out of range.");
                }
                if (value.comment)
                {
                    header.DocComment(DocText(*value.comment));
                }
                header.Line(value.name + " = " + std::to_string(value.ordinal) + ",");
            }
            header.Dedent();
            header.Line("};");
            header.Line();
            header.DocComment("Gets the name of a " + protocol_enum.name +
                              " value.\n\n"
                              "@param value the value to get the name of.\n"
                              "@return the name of the value, or \"Unrecognized(N)\" for unrecognized values.");
            header.Line("EOLIB_API std::string ToString(" + protocol_enum.name + " value);");
            header.Line();
            header.DocComment("Writes the name of a " + protocol_enum.name +
                              " value to a stream.\n\n"
                              "@param stream the stream to write to.\n"
                              "@param value the value to write the name of.\n"
                              "@return the stream.\n"
                              "@see ToString(" +
                              protocol_enum.name + ")");
            header.Line("EOLIB_API std::ostream& operator<<(std::ostream& stream, " + protocol_enum.name + " value);");
            header.Line();

            source.Open("std::string ToString(" + protocol_enum.name + " value)");
            source.Open("switch (value)");
            for (const auto& value : protocol_enum.values)
            {
                source.Line("case " + protocol_enum.name + "::" + value.name + ":");
                source.Indent();
                source.Line("return \"" + value.name + "\";");
                source.Dedent();
            }
            source.Line("default:");
            source.Indent();
            source.Line("return \"Unrecognized(\" + std::to_string(static_cast<int>(value)) + \")\";");
            source.Dedent();
            source.Close();
            source.Close();
            source.Line();
            source.Open("std::ostream& operator<<(std::ostream& stream, " + protocol_enum.name + " value)");
            source.Line("return stream << ToString(value);");
            source.Close();
            source.Line();
        }

        EndNamespace(header, file);
        EndNamespace(source, file);
        AddOutput(result, "include/" + HeaderPath(file, "enums"), header);
        AddOutput(result, "src/" + file.IncludeDir() + "/enums.cpp", source);
    }

    /// Adds includes for custom types referenced by the objects, which are defined in other files.
    void DependencyIncludes(const ProtocolFile& file, const std::vector<const std::vector<Instruction>*>& objects,
                            std::set<std::string>& includes)
    {
        std::vector<const Type*> referenced;
        for (const auto* instructions : objects)
        {
            CollectReferencedTypes(*instructions, types_, referenced);
        }

        for (const auto* type : referenced)
        {
            if (type->file == &file)
            {
                continue;
            }
            includes.insert(HeaderPath(*type->file, type->kind == TypeKind::Enum ? "enums" : "structs"));
        }
    }

    static std::set<std::string> SystemIncludes()
    {
        return {"cstdint", "optional", "string", "string_view", "variant", "vector"};
    }

    static std::set<std::string> SourceSystemIncludes()
    {
        return {"cstddef", "string", "variant"};
    }

    /// Sorts structs so that each struct is defined after the structs it contains (from the same file).
    std::vector<const ProtocolStruct*> SortStructs(const ProtocolFile& file)
    {
        std::vector<const ProtocolStruct*> result;
        std::set<const ProtocolStruct*> visited;
        std::set<const ProtocolStruct*> visiting;

        std::function<void(const ProtocolStruct&)> visit = [&](const ProtocolStruct& protocol_struct)
        {
            if (visited.count(&protocol_struct) != 0)
            {
                return;
            }
            if (visiting.count(&protocol_struct) != 0)
            {
                throw GeneratorError(file.path.string() + ": " + protocol_struct.name + " has a circular dependency.");
            }
            visiting.insert(&protocol_struct);

            std::vector<const Type*> referenced;
            CollectReferencedTypes(protocol_struct.instructions, types_, referenced);
            for (const auto* type : referenced)
            {
                if (type->kind == TypeKind::Struct && type->file == &file)
                {
                    visit(*type->struct_definition);
                }
            }

            visiting.erase(&protocol_struct);
            visited.insert(&protocol_struct);
            result.push_back(&protocol_struct);
        };

        for (const auto& protocol_struct : file.structs)
        {
            visit(protocol_struct);
        }
        return result;
    }

    void GenerateStructs(const ProtocolFile& file, std::vector<OutputFile>& result)
    {
        const auto layout = FileLayout::Of(file);

        std::vector<const std::vector<Instruction>*> objects;
        for (const auto& protocol_struct : file.structs)
        {
            objects.push_back(&protocol_struct.instructions);
        }

        std::set<std::string> includes = {"eolib/export.hpp", "eolib/protocol/serializable.hpp",
                                          "eolib/data/eo_reader.hpp", "eolib/data/eo_writer.hpp"};
        if (layout.has_enums)
        {
            includes.insert(HeaderPath(file, "enums"));
        }
        DependencyIncludes(file, objects, includes);

        CodeWriter header;
        BeginHeader(header);
        Includes(header, includes, SystemIncludes());
        BeginNamespace(header, file);

        CodeWriter source;
        source.Line(BANNER);
        source.Line();
        Includes(source, {HeaderPath(file, "structs"), "eolib/errors.hpp", "eolib/protocol/detail/serialization.hpp"},
                 SourceSystemIncludes());
        BeginNamespace(source, file);

        for (const auto* protocol_struct : SortStructs(file))
        {
            ObjectGenerator generator(types_, file, protocol_struct->name, protocol_struct->name, Context{});
            generator.GenerateInstructions(protocol_struct->instructions);
            generator.Finish(protocol_struct->comment, std::nullopt, header, source);
            header.Line();
        }

        EndNamespace(header, file);
        EndNamespace(source, file);
        AddOutput(result, "include/" + HeaderPath(file, "structs"), header);
        AddOutput(result, "src/" + file.IncludeDir() + "/structs.cpp", source);
    }

    std::string PacketSuffix(const ProtocolFile& file) const
    {
        const std::string last = file.namespace_parts.empty() ? "" : file.namespace_parts.back();
        if (last == "client")
        {
            return "ClientPacket";
        }
        if (last == "server")
        {
            return "ServerPacket";
        }
        throw GeneratorError(file.path.string() + ": packets are only allowed in client or server protocol files.");
    }

    std::string PacketClassName(const ProtocolFile& file, const ProtocolPacket& packet) const
    {
        return packet.family + packet.action + PacketSuffix(file);
    }

    void ValidatePacketIds(const ProtocolFile& file)
    {
        const Type& family_type = types_.Get("PacketFamily");
        const Type& action_type = types_.Get("PacketAction");
        if (family_type.kind != TypeKind::Enum || action_type.kind != TypeKind::Enum)
        {
            throw GeneratorError("PacketFamily and PacketAction must be enums.");
        }

        const auto has_value = [](const Type& type, const std::string& name)
        {
            return std::any_of(type.enum_definition->values.begin(), type.enum_definition->values.end(),
                               [&](const ProtocolEnumValue& value) { return value.name == name; });
        };

        std::set<std::pair<std::string, std::string>> ids;
        for (const auto& packet : file.packets)
        {
            if (!has_value(family_type, packet.family))
            {
                throw GeneratorError(file.path.string() + ": " + packet.family + " is not a valid PacketFamily.");
            }
            if (!has_value(action_type, packet.action))
            {
                throw GeneratorError(file.path.string() + ": " + packet.action + " is not a valid PacketAction.");
            }
            if (!ids.emplace(packet.family, packet.action).second)
            {
                throw GeneratorError(file.path.string() + ": " + packet.family + "_" + packet.action +
                                     " packet cannot be redefined in the same file.");
            }
        }
    }

    void GeneratePackets(const ProtocolFile& file, std::vector<OutputFile>& result)
    {
        ValidatePacketIds(file);
        const auto layout = FileLayout::Of(file);
        const Type& family_type = types_.Get("PacketFamily");

        std::vector<const std::vector<Instruction>*> objects;
        for (const auto& packet : file.packets)
        {
            objects.push_back(&packet.instructions);
        }

        std::set<std::string> includes = {"eolib/export.hpp", "eolib/protocol/net/packet.hpp",
                                          "eolib/data/eo_reader.hpp", "eolib/data/eo_writer.hpp",
                                          HeaderPath(*family_type.file, "enums")};
        if (layout.has_enums)
        {
            includes.insert(HeaderPath(file, "enums"));
        }
        if (layout.has_structs)
        {
            includes.insert(HeaderPath(file, "structs"));
        }
        DependencyIncludes(file, objects, includes);

        CodeWriter header;
        BeginHeader(header);
        Includes(header, includes, SystemIncludes());
        BeginNamespace(header, file);

        CodeWriter source;
        source.Line(BANNER);
        source.Line();
        Includes(source, {HeaderPath(file, "packets"), "eolib/errors.hpp", "eolib/protocol/detail/serialization.hpp"},
                 SourceSystemIncludes());
        BeginNamespace(source, file);

        for (const auto& packet : file.packets)
        {
            const std::string name = PacketClassName(file, packet);
            ObjectGenerator generator(types_, file, name, name, Context{});
            generator.GenerateInstructions(packet.instructions);
            generator.Finish(packet.comment, PacketInfo{packet.family, packet.action}, header, source);
            header.Line();
        }

        EndNamespace(header, file);
        EndNamespace(source, file);
        AddOutput(result, "include/" + HeaderPath(file, "packets"), header);
        AddOutput(result, "src/" + file.IncludeDir() + "/packets.cpp", source);
    }

    void GeneratePacketFactory(const ProtocolFile& file, std::vector<OutputFile>& result)
    {
        const Type& family_type = types_.Get("PacketFamily");
        const std::string side = PacketSuffix(file) == "ClientPacket" ? "client" : "server";

        CodeWriter header;
        BeginHeader(header);
        Includes(header,
                 {"eolib/export.hpp", "eolib/data/eo_reader.hpp", "eolib/protocol/net/packet.hpp",
                  HeaderPath(*family_type.file, "enums")},
                 {"memory"});
        BeginNamespace(header, file);
        header.DocComment("Creates " + side + " packets from packet family and action identifiers.");
        header.Line("class EOLIB_API PacketFactory");
        header.Line("{");
        header.Line("public:");
        header.Indent();
        header.Line("PacketFactory() = delete;");
        header.Line();
        header.DocComment("Creates a default-initialized " + side +
                          " packet with the specified family and action.\n\n"
                          "@param family the packet family.\n"
                          "@param action the packet action.\n"
                          "@return the packet, or nullptr if no " +
                          side + " packet has the specified family and action.");
        header.Line("static std::unique_ptr<Packet> Create(PacketFamily family, PacketAction action);");
        header.Line();
        header.DocComment("Checks whether a " + side +
                          " packet exists with the specified family and action, without creating it.\n\n"
                          "@param family the packet family.\n"
                          "@param action the packet action.\n"
                          "@return true if a " +
                          side + " packet has the specified family and action, otherwise false.");
        header.Line("static bool Contains(PacketFamily family, PacketAction action) noexcept;");
        header.Line();
        header.DocComment("Creates a " + side +
                          " packet with the specified family and action, and deserializes it from the reader.\n\n"
                          "@param family the packet family.\n"
                          "@param action the packet action.\n"
                          "@param reader the reader that the packet data will be read from.\n"
                          "@return the packet, or nullptr if no " +
                          side + " packet has the specified family and action.");
        header.Line("static std::unique_ptr<Packet> Deserialize(PacketFamily family, PacketAction action, "
                    "data::EoReader& reader);");
        header.Dedent();
        header.Line("};");
        EndNamespace(header, file);

        std::map<std::string, std::vector<const ProtocolPacket*>> by_family;
        std::vector<std::string> family_order;
        for (const auto& packet : file.packets)
        {
            if (by_family.count(packet.family) == 0)
            {
                family_order.push_back(packet.family);
            }
            by_family[packet.family].push_back(&packet);
        }

        CodeWriter source;
        source.Line(BANNER);
        source.Line();
        Includes(source, {HeaderPath(file, "packet_factory"), HeaderPath(file, "packets")}, {"memory"});
        BeginNamespace(source, file);

        source.Open("std::unique_ptr<Packet> PacketFactory::Create(PacketFamily family, PacketAction action)");
        source.Open("switch (family)");
        for (const auto& family : family_order)
        {
            source.Line("case PacketFamily::" + family + ":");
            source.Indent();
            source.Open("switch (action)");
            for (const auto* packet : by_family[family])
            {
                source.Line("case PacketAction::" + packet->action + ":");
                source.Indent();
                source.Line("return std::make_unique<" + PacketClassName(file, *packet) + ">();");
                source.Dedent();
            }
            source.Line("default:");
            source.Indent();
            source.Line("return nullptr;");
            source.Dedent();
            source.Close();
            source.Dedent();
        }
        source.Line("default:");
        source.Indent();
        source.Line("return nullptr;");
        source.Dedent();
        source.Close();
        source.Close();
        source.Line();

        source.Open("bool PacketFactory::Contains(PacketFamily family, PacketAction action) noexcept");
        source.Open("switch (family)");
        for (const auto& family : family_order)
        {
            source.Line("case PacketFamily::" + family + ":");
            source.Indent();
            source.Open("switch (action)");
            for (const auto* packet : by_family[family])
            {
                source.Line("case PacketAction::" + packet->action + ":");
            }
            source.Indent();
            source.Line("return true;");
            source.Dedent();
            source.Line("default:");
            source.Indent();
            source.Line("return false;");
            source.Dedent();
            source.Close();
            source.Dedent();
        }
        source.Line("default:");
        source.Indent();
        source.Line("return false;");
        source.Dedent();
        source.Close();
        source.Close();
        source.Line();

        source.Open("std::unique_ptr<Packet> PacketFactory::Deserialize(PacketFamily family, PacketAction action, "
                    "data::EoReader& reader)");
        source.Line("auto packet = Create(family, action);");
        source.Open("if (packet != nullptr)");
        source.Line("packet->Deserialize(reader);");
        source.Close();
        source.Line("return packet;");
        source.Close();

        EndNamespace(source, file);
        AddOutput(result, "include/" + HeaderPath(file, "packet_factory"), header);
        AddOutput(result, "src/" + file.IncludeDir() + "/packet_factory.cpp", source);
    }

    static std::vector<std::string> FileHeaders(const ProtocolFile& file)
    {
        const auto layout = FileLayout::Of(file);
        std::vector<std::string> headers;
        if (layout.has_enums)
        {
            headers.push_back(HeaderPath(file, "enums"));
        }
        if (layout.has_structs)
        {
            headers.push_back(HeaderPath(file, "structs"));
        }
        if (layout.has_packets)
        {
            headers.push_back(HeaderPath(file, "packets"));
            headers.push_back(HeaderPath(file, "packet_factory"));
        }
        return headers;
    }

    void GenerateUmbrella(const ProtocolFile& file, std::vector<OutputFile>& result)
    {
        CodeWriter header;
        BeginHeader(header);
        auto headers = FileHeaders(file);
        if (file.namespace_parts.size() == 1 && file.namespace_parts[0] == "net")
        {
            headers.push_back("eolib/protocol/net/packet.hpp");
        }
        std::sort(headers.begin(), headers.end());
        for (const auto& include : headers)
        {
            header.Line("#include \"" + include + "\"");
        }
        AddOutput(result, "include/" + file.IncludeDir() + ".hpp", header);
    }

    void GenerateRootUmbrella(std::vector<OutputFile>& result)
    {
        std::vector<std::string> headers;
        for (const auto& file : files_)
        {
            if (file.namespace_parts.empty())
            {
                for (const auto& include : FileHeaders(file))
                {
                    headers.push_back(include);
                }
            }
            else
            {
                headers.push_back(file.IncludeDir() + ".hpp");
            }
        }
        std::sort(headers.begin(), headers.end());

        CodeWriter header;
        BeginHeader(header);
        for (const auto& include : headers)
        {
            header.Line("#include \"" + include + "\"");
        }
        AddOutput(result, "include/eolib/protocol.hpp", header);
    }
};

} // namespace

std::vector<OutputFile> GenerateProtocol(const std::vector<ProtocolFile>& files, TypeRegistry& types)
{
    return ProtocolGenerator(files, types).Generate();
}

} // namespace eolib::generator
