#include "generated_file.hpp"

#include <fstream>
#include <iterator>
#include <stdexcept>
#include <utility>

namespace eolib::generator
{

bool OutputFile::WriteIfChanged(const std::filesystem::path& output_root) const
{
    const auto file_path = output_root / path;
    if (std::filesystem::exists(file_path))
    {
        std::ifstream existing(file_path, std::ios::binary);
        if (existing &&
            std::string(std::istreambuf_iterator<char>(existing), std::istreambuf_iterator<char>()) == content)
        {
            return false;
        }
    }

    std::filesystem::create_directories(file_path.parent_path());
    std::ofstream stream(file_path, std::ios::binary | std::ios::trunc);
    if (!stream)
    {
        throw std::runtime_error("Failed to open " + file_path.string() + " for writing.");
    }
    stream << content;
    if (!stream)
    {
        throw std::runtime_error("Failed to write " + file_path.string() + ".");
    }
    return true;
}

GeneratedFile::GeneratedFile(std::string path, Kind kind)
    : path_(std::move(path))
{
    Line("// Generated by eolib-protocol-gen from eo-protocol. Do not edit.");
    Line();
    if (kind == Kind::Header)
    {
        Line("#pragma once");
        Line();
    }
}

OutputFile GeneratedFile::ToOutput() const
{
    return OutputFile{path_, ToString()};
}

} // namespace eolib::generator
