#pragma once

#include "code_writer.hpp"
#include "doc_comment.hpp"
#include "errors.hpp"
#include "model.hpp"
#include "serialization_code.hpp"
#include "types.hpp"

#include <map>
#include <optional>
#include <set>
#include <string>
#include <vector>

namespace eolib::generator
{

/// A field that later instructions in the same class can refer to, e.g. as a length or switch field.
struct FieldData
{
    std::string identifier;
    const Type* type = nullptr;
    int offset = 0;
    bool array = false;
    bool optional = false;
    bool length_field = false;
    bool hardcoded = false;
};

/// The state of the instructions generated so far for a class, used to validate the instructions that follow.
struct Context
{
    bool chunked = false;
    bool reached_optional = false;
    bool reached_dummy = false;
    /// Whether a non-delimited array without a length has been reached. It consumes the rest of the data (or chunk), so
    /// it must be the final element.
    bool reached_unsized_array = false;
    std::map<std::string, FieldData> accessible_fields;
    /// Length field name -> whether it has been referenced by a field.
    std::map<std::string, bool> length_field_referenced;
    /// Length field name -> the instruction that references it.
    std::map<std::string, const Instruction*> length_references;
    /// Identifiers of all members of the class, so generated locals and members don't conflict with them.
    std::set<std::string> scope_identifiers;
};

/// The family and action of a packet class.
struct PacketInfo
{
    std::string family;
    std::string action;
};

/// The code generated for the members of a class, built up as its instructions are generated.
struct ObjectCode
{
    /// Member declarations, including nested types.
    CodeWriter members;
    /// Out-of-line definitions of the member functions of nested types.
    CodeWriter nested_definitions;
    /// The body of Serialize.
    CodeWriter serialize;
    /// The body of Deserialize.
    CodeWriter deserialize;
    /// Identifiers of the data members, which are compared by operator== and included in ToString.
    std::vector<std::string> value_members;
};

/// Generates a single class (struct, packet or switch case). Follows the semantics of eolib-java's
/// ObjectCodeGenerator and FieldCodeGenerator. Switches are generated by SwitchGenerator.
class ObjectGenerator
{
public:
    /// Creates the generator for a class. qualified_name is the class name relative to the namespace of the file,
    /// e.g. "Outer::Inner" for a switch case. context is the state of the enclosing class, for a switch case.
    ObjectGenerator(TypeRegistry& types, const ProtocolFile& file, std::string class_name, std::string qualified_name,
                    Context context);

    /// Generates the members for the instructions of the class.
    /// @throws GeneratorError if the instructions are invalid.
    void GenerateInstructions(const std::vector<Instruction>& instructions);

    /// Gets the state after the instructions that have been generated.
    const Context& GetContext() const;

    /// Writes the class declaration, and the out-of-line member definitions.
    /// @throws GeneratorError if a length field is not referenced by another field.
    void Finish(const std::optional<std::string>& comment, const std::optional<PacketInfo>& packet,
                CodeWriter& declaration, CodeWriter& definitions);

private:
    TypeRegistry& types_;
    const ProtocolFile& file_;
    std::string class_name_;
    std::string qualified_name_;
    Context context_;
    ObjectCode code_;
    SerializationCode serialization_;
    DocComment docs_;
    bool needs_old_writer_length_ = false;
    bool declared_reached_null_optional_ = false;
    bool uses_chunked_ = false;

    // Set while generating an instruction: true if a <dummy> follows the instruction in the same list.
    bool dummy_follows_ = false;

    GeneratorError Error(const std::string& message) const;

    /// Records identifiers and length field references for the instructions of this object.
    void PrepareScope(const std::vector<Instruction>& instructions);

    /// Gets a name for a local variable that doesn't conflict with a member or a reserved identifier.
    std::string LocalName(const std::string& base) const;

    void GenerateInstructionList(const std::vector<Instruction>& instructions);
    void GenerateInstruction(const Instruction& instruction);

    void CheckOptionalField(bool optional) const;
    void CheckUniqueName(const std::string& name) const;

    /// Declares a data member, followed by a blank line.
    void DeclareMember(const std::string& cpp_type, const FieldData& field);
    void AddMemberDocs(const Instruction& instruction, const Type& type, bool array,
                       const std::optional<std::string>& remarks = std::nullopt);

    /// Gets the largest length that the length field referenced by an instruction can hold, or nullopt if the length
    /// doesn't come from an accessible length field.
    std::optional<long long> LengthFieldMax(const Instruction& instruction) const;

    /// Begins the optional guard for serialization, if the field is optional.
    void BeginSerializeOptional(const FieldData& field);
    void BeginDeserializeOptional(const Type& type, bool array);

    /// For a length field reference in a field/array, returns the expression used when deserializing.
    std::optional<std::string> DeserializeLengthExpression(const std::optional<std::string>& length) const;
    void ValidateLengthAttribute(const std::optional<std::string>& length);

    /// Emits a check that a sized field fits its length: exactly equal, or at most the limit if allow_shorter is set.
    void GenerateSerializeLengthCheck(const std::string& identifier, const std::string& size_expression,
                                      const std::string& limit, bool allow_shorter);

    void GenerateField(const Instruction& instruction);
    void ValidateField(const Instruction& instruction, const Type& type);
    FieldData DeclareField(const Instruction& instruction, const Type& type);
    void GenerateSerializeField(const Instruction& instruction, const Type& type, const FieldData& field);
    void GenerateDeserializeField(const Instruction& instruction, const Type& type, const FieldData& field);

    void GenerateArray(const Instruction& instruction);
    void ValidateArray(const Instruction& instruction, const Type& type);
    FieldData DeclareArray(const Instruction& instruction, const Type& type);
    void GenerateSerializeArray(const Instruction& instruction, const Type& type, const FieldData& field,
                                const std::string& container, bool trailing_delimiter);
    void GenerateDeserializeArray(const Instruction& instruction, const Type& type, const FieldData& field,
                                  const std::string& container, bool trailing_delimiter);

    void GenerateLength(const Instruction& instruction);
    void GenerateDummy(const Instruction& instruction);
    void GenerateSwitch(const Instruction& instruction);
    void GenerateChunked(const Instruction& instruction);
    void GenerateBreak();

    void WriteDeclaration(const std::optional<std::string>& comment, const std::optional<PacketInfo>& packet,
                          CodeWriter& declaration);
    void WriteSerializationDefinitions(CodeWriter& definitions) const;
    void WriteToStringDefinition(CodeWriter& definitions) const;
    void WriteEqualityDefinitions(CodeWriter& definitions) const;
};

} // namespace eolib::generator
