#include "property_emitter.hpp"

#include "code_writer.hpp"
#include "errors.hpp"
#include "names.hpp"

#include <functional>
#include <map>
#include <set>
#include <string>

namespace eolib::generator
{

namespace
{

constexpr const char* BANNER = "// Generated by eolib-protocol-gen from eo-protocol. Do not edit.";

std::string PacketSide(const ProtocolFile& file)
{
    const std::string last = file.namespace_parts.empty() ? "" : file.namespace_parts.back();
    if (last == "client" || last == "server")
    {
        return last;
    }
    throw GeneratorError(file.path.string() + ": packets are only allowed in client or server protocol files.");
}

std::string PacketClassName(const ProtocolFile& file, const ProtocolPacket& packet)
{
    const std::string side = PacketSide(file);
    return packet.family + packet.action + (side == "client" ? "ClientPacket" : "ServerPacket");
}

/// Generates the FromProperties factory functions that create generated objects from JSON properties. Each object has
/// a specialization of `template <typename T> T FromProperties(const Json& properties)`, where properties is the array
/// of property objects.
class PropertyGenerator
{
public:
    PropertyGenerator(const std::vector<ProtocolFile>& files, TypeRegistry& types)
        : files_(files),
          types_(types)
    {
    }

    std::vector<OutputFile> Generate()
    {
        // Only the packets, and the structs that they reference, are generated.
        for (const auto& file : files_)
        {
            for (const auto& packet : file.packets)
            {
                GenerateObject(file, file.Namespace() + "::" + PacketClassName(file, packet),
                               packet.family + packet.action, packet.instructions);
            }
        }

        CodeWriter output;
        output.Line(BANNER);
        output.Line();
        output.Line("#include \"protocol/captured_packet_properties.hpp\"");
        output.Line();
        output.Line("#include \"eolib/protocol.hpp\"");
        output.Line();
        output.Line("#include <memory>");
        output.Line("#include <string>");
        output.Line("#include <variant>");
        output.Line();
        output.Line("namespace eolib::test");
        output.Line("{");
        output.Line();
        output.Line("namespace");
        output.Line("{");
        output.Line();
        output.Line("using namespace eolib::test::detail;");
        output.Line();
        output.Line("/// Creates an object of type T with its fields set from the properties array. Each type has an");
        output.Line("/// explicit specialization below.");
        output.Line("template <typename T>");
        output.Line("T FromProperties(const Json& properties);");
        output.Line();
        output.Append(declarations_);
        output.Line();
        output.Append(definitions_);
        output.TrimTrailingBlankLine();
        output.Line();
        output.Line("} // namespace");
        output.Line();

        for (const auto& file : files_)
        {
            if (!file.packets.empty())
            {
                GeneratePacketFunctions(file, output);
            }
        }

        output.TrimTrailingBlankLine();
        output.Line();
        output.Line("} // namespace eolib::test");
        return {OutputFile{"captured_packet_properties.cpp", output.ToString()}};
    }

private:
    const std::vector<ProtocolFile>& files_;
    TypeRegistry& types_;
    CodeWriter declarations_;
    CodeWriter definitions_;
    std::set<const ProtocolStruct*> generated_structs_;

    std::string CppTypeName(const Type& type) const
    {
        switch (type.kind)
        {
            case TypeKind::Enum:
            case TypeKind::Struct:
                return type.file->Namespace() + "::" + type.name;
            default:
                throw GeneratorError("Unhandled custom type " + type.name);
        }
    }

    /// Returns an expression for the value of a non-struct property.
    std::string ValueExpression(const Type& type, const std::string& property) const
    {
        switch (type.kind)
        {
            case TypeKind::Integer:
                return "IntValue(" + property + ")";
            case TypeKind::Bool:
                return "BoolValue(" + property + ")";
            case TypeKind::String:
                return "StringValue(" + property + ")";
            case TypeKind::Blob:
                return "BlobValue(" + property + ")";
            case TypeKind::Enum:
                return "static_cast<" + CppTypeName(type) + ">(IntValue(" + property + "))";
            case TypeKind::Struct:
                break;
        }
        throw GeneratorError("Unhandled type for property value: " + type.name);
    }

    /// Returns an expression for the value of a property, including struct properties.
    std::string PropertyExpression(const Type& type, const std::string& property) const
    {
        if (type.kind == TypeKind::Struct)
        {
            return "FromProperties<" + CppTypeName(type) + ">(Children(" + property + "))";
        }
        return ValueExpression(type, property);
    }

    struct ObjectBody
    {
        CodeWriter branches;
        std::vector<std::string> ignored_names;
    };

    /// Generates the FromProperties specialization for a struct type, if it hasn't been generated yet.
    void RequireStruct(const Type& type)
    {
        if (type.kind != TypeKind::Struct || !generated_structs_.insert(type.struct_definition).second)
        {
            return;
        }
        GenerateObject(*type.file, CppTypeName(type), "", type.struct_definition->instructions);
    }

    void GenerateObject(const ProtocolFile& file, const std::string& qualified_name, const std::string& dump_prefix,
                        const std::vector<Instruction>& instructions)
    {
        ObjectBody body;
        GenerateInstructions(file, qualified_name, dump_prefix, instructions, body);

        const std::string signature =
            qualified_name + " FromProperties<" + qualified_name + ">(const Json& properties)";
        declarations_.Line("template <>");
        declarations_.Line(signature + ";");

        definitions_.Line("template <>");
        definitions_.Open(signature);
        definitions_.Line(qualified_name + " result;");
        if (body.branches.Empty() && body.ignored_names.empty())
        {
            // A loop would warn about unreachable code (MSVC C4702), since UnknownProperty doesn't return.
            definitions_.Open("if (!properties.empty())");
            definitions_.Line("UnknownProperty(properties.front(), \"" + qualified_name + "\");");
            definitions_.Close();
            definitions_.Line("return result;");
            definitions_.Close();
            definitions_.Line();
            return;
        }
        definitions_.Open("for (const auto& property : properties)");
        definitions_.Line("const std::string& name = Name(property);");
        std::string keyword = "if";
        if (!body.branches.Empty())
        {
            definitions_.Append(body.branches);
            keyword = "else if";
        }
        if (!body.ignored_names.empty())
        {
            std::string condition;
            for (const auto& name : body.ignored_names)
            {
                condition += (condition.empty() ? "" : " || ") + std::string("name == \"") + name + "\"";
            }
            definitions_.Line(keyword + " (" + condition + ")");
            definitions_.Line("{");
            definitions_.Indent();
            definitions_.Line("// Length and hardcoded fields are not stored in the object.");
            definitions_.Close();
            keyword = "else if";
        }
        if (keyword == "if")
        {
            definitions_.Line("UnknownProperty(property, \"" + qualified_name + "\");");
        }
        else
        {
            definitions_.Open("else");
            definitions_.Line("UnknownProperty(property, \"" + qualified_name + "\");");
            definitions_.Close();
        }
        definitions_.Close();
        definitions_.Line("return result;");
        definitions_.Close();
        definitions_.Line();
    }

    void GenerateInstructions(const ProtocolFile& file, const std::string& qualified_name,
                              const std::string& dump_prefix, const std::vector<Instruction>& instructions,
                              ObjectBody& body)
    {
        for (const auto& instruction : instructions)
        {
            switch (instruction.kind)
            {
                case InstructionKind::Field:
                    GenerateField(instruction, body);
                    break;
                case InstructionKind::Array:
                    GenerateArray(instruction, body);
                    break;
                case InstructionKind::Length:
                    body.ignored_names.push_back(*instruction.name);
                    break;
                case InstructionKind::Switch:
                    GenerateSwitch(file, qualified_name, dump_prefix, instruction, body);
                    break;
                case InstructionKind::Chunked:
                    GenerateInstructions(file, qualified_name, dump_prefix, instruction.instructions, body);
                    break;
                case InstructionKind::Dummy:
                case InstructionKind::Break:
                    break;
            }
        }
    }

    void BeginBranch(ObjectBody& body, const std::string& name)
    {
        const std::string keyword = body.branches.Empty() ? "if" : "else if";
        body.branches.Open(keyword + " (name == \"" + name + "\")");
    }

    void GenerateField(const Instruction& instruction, ObjectBody& body)
    {
        if (!instruction.name)
        {
            return;
        }
        if (instruction.value)
        {
            body.ignored_names.push_back(*instruction.name);
            return;
        }

        const Type& type = types_.Get(instruction.type, instruction.length);
        RequireStruct(type);
        const std::string assignment =
            "result." + MemberIdentifier(*instruction.name) + " = " + PropertyExpression(type, "property") + ";";
        BeginBranch(body, *instruction.name);
        if (instruction.optional)
        {
            body.branches.Open("if (HasValue(property))");
            body.branches.Line(assignment);
            body.branches.Close();
        }
        else
        {
            body.branches.Line(assignment);
        }
        body.branches.Close();
    }

    void GenerateArray(const Instruction& instruction, ObjectBody& body)
    {
        const Type& type = types_.Get(instruction.type);
        RequireStruct(type);
        const std::string member = "result." + MemberIdentifier(*instruction.name);
        BeginBranch(body, *instruction.name);

        std::string container = member;
        if (instruction.optional)
        {
            body.branches.Open("if (!HasValue(property))");
            body.branches.Line("continue;");
            body.branches.Close();
            body.branches.Line("auto& values = " + member + ".emplace();");
            container = "values";
        }

        body.branches.Open("for (const auto& element : Children(property))");
        body.branches.Line(container + ".push_back(" + PropertyExpression(type, "element") + ");");
        body.branches.Close();
        body.branches.Close();
    }

    void GenerateSwitch(const ProtocolFile& file, const std::string& qualified_name, const std::string& dump_prefix,
                        const Instruction& instruction, ObjectBody& body)
    {
        const std::string data_type_name = SnakeCaseToPascalCase(instruction.switch_field) + "Data";
        const std::string data_name = instruction.switch_field + "_data";
        const std::string member = "result." + MemberIdentifier(data_name);

        // Generate the case objects first, so their FromProperties specializations are declared before use.
        std::vector<std::pair<std::string, std::string>> data_cases;
        std::vector<std::string> empty_cases;
        for (const auto& protocol_case : instruction.cases)
        {
            const std::string case_type_name =
                data_type_name + (protocol_case.is_default ? std::string("Default") : *protocol_case.value);
            if (protocol_case.instructions.empty())
            {
                empty_cases.push_back(dump_prefix + case_type_name);
                continue;
            }
            const std::string case_qualified_name = qualified_name + "::" + case_type_name;
            GenerateObject(file, case_qualified_name, dump_prefix, protocol_case.instructions);
            data_cases.emplace_back(dump_prefix + case_type_name, case_qualified_name);
        }

        BeginBranch(body, data_name);
        body.branches.Line("const std::string type = TypeName(property);");
        std::string keyword = "if";
        for (const auto& [dump_name, case_qualified_name] : data_cases)
        {
            body.branches.Open(keyword + " (type == \"" + dump_name + "\")");
            body.branches.Line(member + " = FromProperties<" + case_qualified_name + ">(Children(property));");
            body.branches.Close();
            keyword = "else if";
        }
        for (const auto& dump_name : empty_cases)
        {
            body.branches.Open(keyword + " (type == \"" + dump_name + "\")");
            body.branches.Line(member + " = std::monostate();");
            body.branches.Close();
            keyword = "else if";
        }
        if (keyword == "if")
        {
            body.branches.Line("UnknownType(property, \"" + qualified_name + "\");");
        }
        else
        {
            body.branches.Open("else");
            body.branches.Line("UnknownType(property, \"" + qualified_name + "\");");
            body.branches.Close();
        }
        body.branches.Close();
    }

    void GeneratePacketFunctions(const ProtocolFile& file, CodeWriter& output)
    {
        const std::string side = PacketSide(file);
        const std::string net_namespace = types_.Get("PacketFamily").file->Namespace();

        std::map<std::string, std::vector<const ProtocolPacket*>> by_family;
        std::vector<std::string> family_order;
        for (const auto& packet : file.packets)
        {
            if (by_family.count(packet.family) == 0)
            {
                family_order.push_back(packet.family);
            }
            by_family[packet.family].push_back(&packet);
        }

        const auto generate_switch =
            [&](const std::function<void(const ProtocolPacket&)>& generate_case, const std::string& fallback)
        {
            output.Open("switch (family)");
            for (const auto& family : family_order)
            {
                output.Line("case " + net_namespace + "::PacketFamily::" + family + ":");
                output.Indent();
                output.Open("switch (action)");
                for (const auto* packet : by_family[family])
                {
                    output.Line("case " + net_namespace + "::PacketAction::" + packet->action + ":");
                    output.Line("{");
                    output.Indent();
                    generate_case(*packet);
                    output.Close();
                }
                output.Line("default:");
                output.Indent();
                output.Line(fallback);
                output.Dedent();
                output.Close();
                output.Dedent();
            }
            output.Line("default:");
            output.Indent();
            output.Line(fallback);
            output.Dedent();
            output.Close();
        };

        output.Line("namespace " + side);
        output.Line("{");
        output.Line();

        output.Open("std::unique_ptr<" + net_namespace + "::Packet> PacketFromProperties(" + net_namespace +
                    "::PacketFamily family, " + net_namespace + "::PacketAction action, const Json& properties)");
        generate_switch(
            [&](const ProtocolPacket& packet)
            {
                const std::string packet_type = file.Namespace() + "::" + PacketClassName(file, packet);
                output.Line("return std::make_unique<" + packet_type + ">(FromProperties<" + packet_type +
                            ">(properties));");
            },
            "return nullptr;");
        output.Close();
        output.Line();

        output.Open("bool PacketsEqual(const " + net_namespace + "::Packet& a, const " + net_namespace +
                    "::Packet& b)");
        output.Open("if (a.Family() != b.Family() || a.Action() != b.Action())");
        output.Line("return false;");
        output.Close();
        output.Line("const auto family = a.Family();");
        output.Line("const auto action = a.Action();");
        generate_switch(
            [&](const ProtocolPacket& packet)
            { output.Line("return EqualAs<" + file.Namespace() + "::" + PacketClassName(file, packet) + ">(a, b);"); },
            "return false;");
        output.Close();
        output.Line();

        output.Line("} // namespace " + side);
        output.Line();
    }
};

} // namespace

std::vector<OutputFile> GenerateCapturedPacketProperties(const std::vector<ProtocolFile>& files, TypeRegistry& types)
{
    return PropertyGenerator(files, types).Generate();
}

} // namespace eolib::generator
